import { type SchemaTypeDefinition } from 'sanity'
import { officerType } from './officer'
import { fixtureType } from './fixture'
import { galleryImageType } from './galleryImage'
import { aboutPageType } from './aboutPage'
import { historyPageType } from './historyPage'
import { officersPageType } from './officersPage'
import { honoursPageType } from './honoursPage'
import { captainType } from './captain'
import { timEdwardsTrophyType } from './timEdwardsTrophy'
import { goldenPedroType } from './goldenPedro'
import { fixturesPageType } from './fixturesPage'
import { seasonType } from './season'
import { toursPageType } from './toursPage'
import { galleryPageType } from './galleryPage'
import { contactPageType } from './contactPage'
import { fosPageType } from './fosPage'
import { fosGalleryPageType } from './fosGalleryPage'
import { partnerType } from './partner'
import { fosWinnerType } from './fosWinner'
import { getInvolvedPageType } from './getInvolvedPage'
import { fosRoundupPageType } from './fosRoundupPage'

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [officerType, fixtureType, galleryImageType, aboutPageType, historyPageType, officersPageType, honoursPageType, captainType, timEdwardsTrophyType, goldenPedroType, fixturesPageType, seasonType, toursPageType, galleryPageType, contactPageType, fosPageType, fosGalleryPageType, partnerType, fosWinnerType, getInvolvedPageType, fosRoundupPageType],
}
